<?php
declare(strict_types=1);
require_once __DIR__.'/../../packages/core/src/Storage/StorageAdapter.php';
require_once __DIR__.'/../../packages/core/src/Storage/AwsSigV4.php';
require_once __DIR__.'/../../packages/core/src/Storage/S3StorageAdapter.php';
require_once __DIR__.'/../../packages/core/src/Storage/LocalFilesystemAdapter.php';
require_once __DIR__.'/../../packages/core/src/Storage/StorageMigrator.php';
use MCMA\Core\Storage\S3StorageAdapter;use MCMA\Core\Storage\LocalFilesystemAdapter;use MCMA\Core\Storage\StorageMigrator;
$objects=[];
$requester=function(string $method,string $url,array $headers,string $body)use(&$objects):array{$parts=parse_url($url);$path=(string)($parts['path']??'');parse_str((string)($parts['query']??''),$query);if($path==='/bucket'||$path==='/bucket/'){$wanted=(string)($query['prefix']??'');$xml='<ListBucketResult><IsTruncated>false</IsTruncated>';foreach($objects as $key=>$obj)if($wanted===''||str_starts_with($key,$wanted))$xml.='<Contents><Key>'.htmlspecialchars(rawurlencode($key),ENT_XML1).'</Key></Contents>';$xml.='</ListBucketResult>';return[200,$xml,[]];}$prefix='/bucket/';if(!str_starts_with($path,$prefix))return[404,'',[]];$key=rawurldecode(substr($path,strlen($prefix)));if($method==='HEAD')return isset($objects[$key])?[200,'',['etag'=>'"'.$objects[$key]['etag'].'"']]:[404,'',[]];if($method==='GET')return isset($objects[$key])?[200,$objects[$key]['bytes'],['etag'=>'"'.$objects[$key]['etag'].'"']]:[404,'',[]];if($method==='PUT'){if(($headers['if-none-match']??null)==='*'&&isset($objects[$key]))return[412,'',[]];if(isset($headers['if-match'])){$want=trim((string)$headers['if-match'],'"');if(!isset($objects[$key])||!hash_equals($want,$objects[$key]['etag']))return[412,'',[]];}$etag=md5($body);$objects[$key]=['bytes'=>$body,'etag'=>$etag];return[200,'',['etag'=>'"'.$etag.'"']];}return[405,'',[]];};
$base=sys_get_temp_dir().'/mcma-s3-migration-'.bin2hex(random_bytes(4));$src=$base.'/src';$dst=$base.'/dst';
function rr(string $d):void{if(!is_dir($d))return;foreach(scandir($d)?:[] as $i){if($i==='.'||$i==='..')continue;$p=$d.DIRECTORY_SEPARATOR.$i;if(is_dir($p))rr($p);else@unlink($p);}@rmdir($d);}try{$local=new LocalFilesystemAdapter($src);$local->put('objects/aa/bb/one.mcma',"object-one\0bytes\n",null,true);$local->put('objects/cc/dd/two.mcma',"object-two\n",null,true);$local->put('manifest.mcma',"manifest-exact\n",null,true);$s3=new S3StorageAdapter('bucket','us-east-1','memory','https://s3.test.local',true,'AKID','SECRET',null,$requester);$r1=StorageMigrator::copy($local,$s3);if($r1['objects_copied']!==2)throw new RuntimeException('Local to S3 count mismatch');$local2=new LocalFilesystemAdapter($dst);$r2=StorageMigrator::copy($s3,$local2);if($r2['objects_copied']!==2)throw new RuntimeException('S3 to Local count mismatch');foreach(['objects/aa/bb/one.mcma','objects/cc/dd/two.mcma','manifest.mcma'] as $loc){$a=$local->get($loc)['bytes'];$b=$local2->get($loc)['bytes'];if(!hash_equals($a,$b))throw new RuntimeException('Byte mismatch after round trip: '.$loc);}echo "MCMA Local-S3-Local byte-preserving migration passed.\n";}finally{rr($base);}
