<?php
declare(strict_types=1);

require_once __DIR__ . '/src/Jcs.php';
require_once __DIR__ . '/src/Crypto.php';
require_once __DIR__ . '/src/KeyStore.php';
require_once __DIR__ . '/src/HistoricalCrypto.php';
require_once __DIR__ . '/src/Storage/StorageAdapter.php';
require_once __DIR__ . '/src/Storage/LocalFilesystemAdapter.php';
require_once __DIR__ . '/src/Storage/GitHubStorageAdapter.php';
require_once __DIR__ . '/src/Storage/AwsSigV4.php';
require_once __DIR__ . '/src/Storage/S3StorageAdapter.php';
require_once __DIR__ . '/src/Storage/WebDavStorageAdapter.php';
require_once __DIR__ . '/src/Storage/StorageFactory.php';
require_once __DIR__ . '/src/Storage/StorageMigrator.php';
require_once __DIR__ . '/src/Security/PermissionEngine.php';
require_once __DIR__ . '/src/Security/VaultPayload.php';
require_once __DIR__ . '/src/Library.php';
require_once __DIR__ . '/src/Knowledge/KnowledgeRecord.php';
require_once __DIR__ . '/src/Knowledge/KnowledgeService.php';
require_once __DIR__ . '/src/Semantic/EmbeddingProvider.php';
require_once __DIR__ . '/src/Semantic/VectorMath.php';
require_once __DIR__ . '/src/Semantic/DeterministicReranker.php';
require_once __DIR__ . '/src/Semantic/SemanticIndexService.php';
require_once __DIR__ . '/src/Ask/GenerationProvider.php';
require_once __DIR__ . '/../connectors/aws/src/BedrockTitanEmbeddingProvider.php';
require_once __DIR__ . '/../connectors/aws/src/BedrockConverseGenerationProvider.php';
require_once __DIR__ . '/../connectors/local/src/OllamaEmbeddingProvider.php';
require_once __DIR__ . '/../connectors/local/src/OllamaGenerationProvider.php';
require_once __DIR__ . '/../connectors/local/src/LlamaCppEmbeddingProvider.php';
require_once __DIR__ . '/../connectors/local/src/LlamaCppGenerationProvider.php';
require_once __DIR__ . '/src/Agent/Librarian.php';
require_once __DIR__ . '/src/Ask/AskService.php';
require_once __DIR__ . '/src/Agent/SecurityAgent.php';
require_once __DIR__ . '/src/LocalLibrary.php';
