<?php
declare(strict_types=1);

namespace MCMA\Core\Ask;

use MCMA\Core\Agent\Librarian;
use MCMA\Core\Knowledge\KnowledgeRecord;
use MCMA\Core\Knowledge\KnowledgeService;
use MCMA\Core\Semantic\EmbeddingProvider;
use MCMA\Core\Semantic\SemanticIndexService;
use RuntimeException;

final class AskService
{
    public function __construct(
        private readonly KnowledgeService $knowledge,
        private readonly ?SemanticIndexService $semantic = null,
        private readonly ?EmbeddingProvider $embeddingProvider = null,
        private readonly ?GenerationProvider $generationProvider = null,
        private readonly ?Librarian $librarian = null
    ) {
        if (($this->semantic === null) !== ($this->embeddingProvider === null)) {
            throw new RuntimeException('Ask semantic retrieval requires both SemanticIndexService and EmbeddingProvider');
        }
    }

    public function ask(
        string $actor,
        string $question,
        bool $currentRequired = false,
        float $minConfidence = 0.75,
        float $minSimilarity = 0.78,
        int $topK = 5,
        bool $rememberGenerated = true,
        array $captureOptions = []
    ): array {
        $normalized = KnowledgeRecord::normalizeIntent($question);

        $exact = $this->knowledge->directAnswer($actor, $question, $currentRequired, $minConfidence);
        if (($exact['reusable'] ?? false) === true && isset($exact['answer'])) {
            $exact['route'] = 'memory-exact';
            $exact['provider_called'] = false;
            return $exact;
        }

        $memoryAttempt = $exact;
        if (($exact['found'] ?? false) !== true && $this->semantic !== null && $this->embeddingProvider !== null) {
            $memoryAttempt = $this->semantic->answer(
                $actor,
                $question,
                $this->embeddingProvider,
                $currentRequired,
                $minConfidence,
                $minSimilarity,
                $topK
            );

            if (($memoryAttempt['reusable'] ?? false) === true && isset($memoryAttempt['answer'])) {
                $memoryAttempt['route'] = 'memory-semantic';
                $memoryAttempt['provider_called'] = false;
                return $memoryAttempt;
            }
        }

        if ($this->generationProvider === null) {
            return [
                'found' => false,
                'reusable' => false,
                'decision' => 'provider-required',
                'route' => 'ask',
                'provider_called' => false,
                'logical_ref' => KnowledgeRecord::logicalRef($question),
                'normalized_intent' => $normalized,
                'memory_attempt' => self::memorySummary($memoryAttempt),
                'reasons' => ['no-reusable-memory', 'generation-provider-not-configured'],
            ];
        }

        $generated = $this->generationProvider->generate($question, [
            'actor' => $actor,
            'current_required' => $currentRequired,
            'memory_attempt' => self::memorySummary($memoryAttempt),
        ]);
        $text = trim((string)($generated['text'] ?? ''));
        if ($text === '') throw new RuntimeException('Generation provider returned an empty answer');

        $storeResult = null;
        $storeReason = null;
        $exactExists = ($exact['found'] ?? false) === true;

        if (!$rememberGenerated) {
            $storeReason = 'remember-generated-disabled';
        } elseif ($exactExists) {
            // Never overwrite an exact disputed/stale/unverified record merely
            // because a model produced fresh text. Preserve its history so a
            // Librarian or validation workflow can decide what replaces it.
            $storeReason = 'existing-exact-record-preserved';
        } elseif ($this->librarian === null) {
            $storeReason = 'librarian-not-configured';
        } else {
            $provenance = [[
                'source_type' => 'model',
                'reference' => $this->generationProvider->id(),
                'note' => 'Generated by mcma ask',
            ]];
            if (is_array($captureOptions['provenance'] ?? null)) {
                $provenance = array_values(array_merge($provenance, $captureOptions['provenance']));
            }

            $freshness = (string)($captureOptions['freshness_class'] ?? 'stable');
            $maxAge = array_key_exists('max_age_seconds', $captureOptions)
                ? ($captureOptions['max_age_seconds'] === null ? null : (int)$captureOptions['max_age_seconds'])
                : ($freshness === 'immutable' ? null : 2592000);

            $storeResult = $this->librarian->remember($question, $text, [
                'answer_format' => 'text',
                'confidence' => (float)($captureOptions['confidence'] ?? 0.5),
                'validation_state' => (string)($captureOptions['validation_state'] ?? 'unverified'),
                'provenance' => $provenance,
                'freshness_class' => $freshness,
                'max_age_seconds' => $maxAge,
                'reuse_policy' => (string)($captureOptions['reuse_policy'] ?? 'reuse-unless-stale'),
                'relations' => is_array($captureOptions['relations'] ?? null) ? $captureOptions['relations'] : [],
            ]);
        }

        $result = [
            'found' => true,
            'reusable' => false,
            'decision' => 'generated',
            'route' => 'provider',
            'provider_called' => true,
            'provider_id' => $this->generationProvider->id(),
            'logical_ref' => KnowledgeRecord::logicalRef($question),
            'normalized_intent' => $normalized,
            'memory_attempt' => self::memorySummary($memoryAttempt),
            'answer' => ['format' => 'text', 'value' => $text],
            'stored' => $storeResult !== null,
        ];

        if ($storeResult !== null) {
            $result['storage'] = [
                'object_id' => $storeResult['object_id'],
                'storage_hash' => $storeResult['storage_hash'],
                'created' => $storeResult['created'] ?? null,
                'validation_state' => (string)($captureOptions['validation_state'] ?? 'unverified'),
                'confidence' => (float)($captureOptions['confidence'] ?? 0.5),
                'semantic_index' => $storeResult['semantic_index'] ?? null,
            ];
        } else {
            $result['store_reason'] = $storeReason;
        }

        if (isset($generated['usage']) && is_array($generated['usage'])) $result['usage'] = $generated['usage'];
        if (array_key_exists('stop_reason', $generated)) $result['stop_reason'] = $generated['stop_reason'];

        return $result;
    }

    private static function memorySummary(array $memory): array
    {
        $keys = [
            'found','reusable','decision','route','reasons','logical_ref',
            'matched_logical_ref','matched_question','object_id','storage_hash',
            'similarity','rerank_score','validation_state','confidence',
            'freshness_class','reuse_policy','stale','stale_index_entries'
        ];

        $summary = [];
        foreach ($keys as $key) {
            if (array_key_exists($key, $memory)) $summary[$key] = $memory[$key];
        }
        return $summary;
    }
}
